name: Deploy GKE Cluster

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Ensure credentials are exported

      - name: Authenticate gcloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run cluster-config.sh
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Pass the secret as an environment variable
        run: |
          chmod +x ./cluster-config.sh
          ./cluster-config.sh