name: Deploy GKE Cluster

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run cluster-config.sh
        run: |
          chmod +x ./cluster-config.sh
          ./cluster-config.sh
